{{- range $app, $config := .Values.apps }}
{{- if $config.image }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $app }}
spec:
  replicas: {{ $config.replicaCount | default $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $app }}
  template:
    metadata:
      labels:
        app: {{ $app }}
    spec:
      containers:
      - name: {{ $app }}
        image: {{ $config.image.repository }}:{{ $config.image.tag }}
        imagePullPolicy: {{ $config.image.pullPolicy }}
        ports:
        - containerPort: {{ $app.service.port }}
      imagePullSecrets:
      - name: {{ $config.imagePullSecrets[0].name }}
{{- end }}
{{- end }}