{{- range $app, $config := .Values.apps }}
{{- if $config.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.service.name }}
spec:
  type: {{ $config.service.type }}
  ports:
  - port: {{ $config.service.port }}
    protocol: TCP
    targetPort: {{ $config.service.port }}
  selector:
    app: {{ $app }}
{{- end }}
{{- end }}